! GENERATED BY VOTCA::XTP::::LOG2MPS (log-file='../DFT_ORCA/water/chelpg.log' : 3 QM atoms)
! N=3 Q[e]=-0.0000000
Units angstrom
  O +0.0000000 +0.0000000 -0.0136970 Rank 0
    -0.7222380
     P +0.8370000
  H +0.7544090 +0.0000000 +0.5842070 Rank 0
    +0.3608580
     P +0.4960000
  H -0.7544090 +0.0000000 +0.5842070 Rank 0
    +0.3613800
     P +0.4960000
